### ISSUE TITLE
The service can fail _while_ it is downloading

### ISSUE THREAD

**Issue by skytreader** [skytreader/ytdlplpy#4]
At that point the queue entry has been consumed but the URL has not really finished downloading. See one sample stacktrace:

```
[download]  37.4% of 4.04GiB at  1.51MiB/s ETA 28:31ERROR: giving up after 0 retries
ytdlpl_1  | Traceback (most recent call last):
ytdlpl_1  |   File "ytdlpl.py", line 30, in <module>
ytdlpl_1  |     ydl.download([url])
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
ytdlpl_1  |     res = self.extract_info(
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
ytdlpl_1  |     return self.process_ie_result(ie_result, download, extra_info)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
ytdlpl_1  |     return self.process_video_result(ie_result, download=download)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
ytdlpl_1  |     self.process_info(new_info)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
ytdlpl_1  |     partial_success = dl(fname, new_info)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
ytdlpl_1  |     return fd.download(name, info)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
ytdlpl_1  |     return self.real_download(filename, info_dict)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 353, in real_download
ytdlpl_1  |     self.report_error('giving up after %s retries' % retries)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
ytdlpl_1  |     self.ydl.report_error(*args, **kargs)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
ytdlpl_1  |     self.trouble(error_message, tb)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
ytdlpl_1  |     raise DownloadError(message, exc_info)
ytdlpl_1  | youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries
ytdlpl_ytdlpl_1 exited with code 1
```

Possible solutions:

- capture exceptions from this line and handle gracefully.
- have a "pending queue", then `BRPOPLPUSH` from the main queue to this pending queue. At start-up, check this pending queue and transfer first all contents into the main queue.

**Comment by skytreader** [comment]
Another possible stacktrace. This was caused by a video that is geoblocked.

```
ytdlpl_1  | ERROR: 1Y9JGjuT1aQ: YouTube said: Unable to extract video data
ytdlpl_1  | Traceback (most recent call last):
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
ytdlpl_1  |     ie_result = ie.extract(url)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
ytdlpl_1  |     ie_result = self._real_extract(url)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1892, in _real_extract
ytdlpl_1  |     raise ExtractorError(
ytdlpl_1  | youtube_dl.utils.ExtractorError: 1Y9JGjuT1aQ: YouTube said: Unable to extract video data
ytdlpl_1  | 
ytdlpl_1  | During handling of the above exception, another exception occurred:
ytdlpl_1  | 
ytdlpl_1  | Traceback (most recent call last):
ytdlpl_1  |   File "ytdlpl.py", line 30, in <module>
ytdlpl_1  |     ydl.download([url])
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
ytdlpl_1  |     res = self.extract_info(
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
ytdlpl_1  |     return self.process_ie_result(ie_result, download, extra_info)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
ytdlpl_1  |     entry_result = self.process_ie_result(entry,
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 867, in process_ie_result
ytdlpl_1  |     return self.extract_info(ie_result['url'],
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 820, in extract_info
ytdlpl_1  |     self.report_error(compat_str(e), e.format_traceback())
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
ytdlpl_1  |     self.trouble(error_message, tb)
ytdlpl_1  |   File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
ytdlpl_1  |     raise DownloadError(message, exc_info)
ytdlpl_1  | youtube_dl.utils.DownloadError: ERROR: 1Y9JGjuT1aQ: YouTube said: Unable to extract video data
```
